### ISSUE TITLE
No mapping file found named 'Duplicate.orm.xml'

### ISSUE THREAD

**Issue by buezu09** [w-vision/ElementManagerBundle#3]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| RFC?             | yes
| Branch?          | master

Since the update of the bundle for Pimcore X, the following error message appears when, for example, the list of available commands is to be displayed:

**No mapping file found named 'Duplicate.orm.xml'**

Specific commands can be entered and also executed.

**To comprehend:**
If the command «bin/console pimcore:list» is entered, the error is thrown.

**Comment by aarongerig** [comment]
Resolved by https://github.com/instride-ch/ElementManagerBundle/commit/053a02989c119c8e6995c08dd128f1535c310b52
